### ISSUE TITLE
Fix flaky tests… 🙄 

### ISSUE THREAD

**Issue by herschel666** [villekulla-nma/booking#62]
<details>
<summary>log I</summary>
<pre><code>
2021-04-04T05:01:47.6577120Z @villekulla-reservations/client: FAIL src/pages/__tests__/reservation-page.test.tsx (6.385 s)
2021-04-04T05:01:47.6647957Z @villekulla-reservations/client:   ● Console
2021-04-04T05:01:47.6650422Z @villekulla-reservations/client:     console.error
2021-04-04T05:01:47.6654344Z @villekulla-reservations/client:       Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
2021-04-04T05:01:47.6657949Z @villekulla-reservations/client:           at ReservationPage (/home/runner/work/villekulla-reservations/villekulla-reservations/client/src/pages/reservation-page.tsx:40:35)
2021-04-04T05:01:47.6662757Z @villekulla-reservations/client:           at Route (/home/runner/work/villekulla-reservations/villekulla-reservations/node_modules/react-router/cjs/react-router.js:470:29)
2021-04-04T05:01:47.6666343Z @villekulla-reservations/client:           at Router (/home/runner/work/villekulla-reservations/villekulla-reservations/node_modules/react-router/cjs/react-router.js:99:30)
2021-04-04T05:01:47.6670804Z @villekulla-reservations/client:           at MemoryRouter (/home/runner/work/villekulla-reservations/villekulla-reservations/node_modules/react-router/cjs/react-router.js:187:35)
2021-04-04T05:01:47.6672732Z @villekulla-reservations/client:       59 |         switch (status) {
2021-04-04T05:01:47.6673932Z @villekulla-reservations/client:       60 |           case 'ok':
2021-04-04T05:01:47.6675849Z @villekulla-reservations/client:     > 61 |             setDescription('');
2021-04-04T05:01:47.6677236Z @villekulla-reservations/client:          |             ^
2021-04-04T05:01:47.6678889Z @villekulla-reservations/client:       62 |             history.push(getBackUrl(params.resourceId, search));
2021-04-04T05:01:47.6681243Z @villekulla-reservations/client:       63 |             break;
2021-04-04T05:01:47.6682496Z @villekulla-reservations/client:       64 |           case 'overlapping':
2021-04-04T05:01:47.6684382Z @villekulla-reservations/client:       at printWarning (../node_modules/react-dom/cjs/react-dom.development.js:67:30)
2021-04-04T05:01:47.6686596Z @villekulla-reservations/client:       at error (../node_modules/react-dom/cjs/react-dom.development.js:43:5)
2021-04-04T05:01:47.6688896Z @villekulla-reservations/client:       at warnAboutUpdateOnUnmountedFiberInDEV (../node_modules/react-dom/cjs/react-dom.development.js:23914:9)
2021-04-04T05:01:47.6691771Z @villekulla-reservations/client:       at scheduleUpdateOnFiber (../node_modules/react-dom/cjs/react-dom.development.js:21840:5)
2021-04-04T05:01:47.6693904Z @villekulla-reservations/client:       at setDescription (../node_modules/react-dom/cjs/react-dom.development.js:16139:5)
2021-04-04T05:01:47.6695933Z @villekulla-reservations/client:       at src/pages/reservation-page.tsx:61:13
2021-04-04T05:01:47.6701663Z @villekulla-reservations/server: PASS src/__tests__/10-server-put-event.ts (7.502 s)
2021-04-04T05:01:47.6737510Z @villekulla-reservations/client:   ● Reservation Page › should render the form & submit creation request
2021-04-04T05:01:47.6739201Z @villekulla-reservations/client:     expect(received).toBe(expected) // Object.is equality
2021-04-04T05:01:47.6741530Z @villekulla-reservations/client:     Expected: "/resources/Uj5SAS740"
2021-04-04T05:01:47.6743099Z @villekulla-reservations/client:     Received: "/resources/Uj5SAS740/create"
2021-04-04T05:01:47.6744309Z @villekulla-reservations/client:       78 |     });
2021-04-04T05:01:47.6745347Z @villekulla-reservations/client:       79 |
2021-04-04T05:01:47.6746871Z @villekulla-reservations/client:     > 80 |     expect(pathname).toBe(`/resources/${resourceId}`);
2021-04-04T05:01:47.6748347Z @villekulla-reservations/client:          |                      ^
2021-04-04T05:01:47.6749805Z @villekulla-reservations/client:       81 |   });
2021-04-04T05:01:47.6751433Z @villekulla-reservations/client:       82 |
2021-04-04T05:01:47.6754969Z @villekulla-reservations/client:       83 |   it('should warn on overlapping events', async () => {
2021-04-04T05:01:47.6758634Z @villekulla-reservations/client:       at Object.<anonymous> (src/pages/__tests__/reservation-page.test.tsx:80:22)
2021-04-04T05:01:47.6761537Z @villekulla-reservations/client:   ● Reservation Page › should warn on overlapping events
2021-04-04T05:01:47.6765241Z @villekulla-reservations/client:     TestingLibraryElementError: Unable to find an element with the text: Die Buchung überschneidet sich mit einer existierenden Buchung.. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.
2021-04-04T05:01:47.6767639Z @villekulla-reservations/client:     [36m<body>[39m
2021-04-04T05:01:47.6768752Z @villekulla-reservations/client:       [36m<div>[39m
2021-04-04T05:01:47.6769870Z @villekulla-reservations/client:         [36m<form[39m
2021-04-04T05:01:47.6771152Z @villekulla-reservations/client:           [33mclass[39m=[32m"css-85"[39m
2021-04-04T05:01:47.6772428Z @villekulla-reservations/client:           [33mmethod[39m=[32m"post"[39m
2021-04-04T05:01:47.6773564Z @villekulla-reservations/client:         [36m>[39m
2021-04-04T05:01:47.6774690Z @villekulla-reservations/client:           [36m<fieldset[39m
2021-04-04T05:01:47.6776012Z @villekulla-reservations/client:             [33mclass[39m=[32m"ms-Stack css-93"[39m
2021-04-04T05:01:47.6777186Z @villekulla-reservations/client:           [36m>[39m
2021-04-04T05:01:47.6778302Z @villekulla-reservations/client:             [36m<legend[39m
2021-04-04T05:01:47.6779539Z @villekulla-reservations/client:               [33mclass[39m=[32m"css-94"[39m
2021-04-04T05:01:47.6781218Z @villekulla-reservations/client:             [36m>[39m
2021-04-04T05:01:47.6782422Z @villekulla-reservations/client:               [0mReservieren[0m
2021-04-04T05:01:47.6783618Z @villekulla-reservations/client:             [36m</legend>[39m
2021-04-04T05:01:47.6784754Z @villekulla-reservations/client:             [36m<dl[39m
2021-04-04T05:01:47.6785975Z @villekulla-reservations/client:               [33mclass[39m=[32m"css-88"[39m
2021-04-04T05:01:47.6787105Z @villekulla-reservations/client:             [36m>[39m
2021-04-04T05:01:47.6788228Z @villekulla-reservations/client:               [36m<div[39m
2021-04-04T05:01:47.6789535Z @villekulla-reservations/client:                 [33mclass[39m=[32m"ms-Stack css-95"[39m
2021-04-04T05:01:47.6790709Z @villekulla-reservations/client:               [36m>[39m
2021-04-04T05:01:47.6791817Z @villekulla-reservations/client:                 [36m<dt[39m
2021-04-04T05:01:47.6793036Z @villekulla-reservations/client:                   [33mclass[39m=[32m"css-96"[39m
2021-04-04T05:01:47.6794579Z @villekulla-reservations/client:                 [36m>[39m
2021-04-04T05:01:47.6795937Z @villekulla-reservations/client:                   [0mBeginn[0m
2021-04-04T05:01:47.6797083Z @villekulla-reservations/client:                 [36m</dt>[39m
2021-04-04T05:01:47.6798215Z @villekulla-reservations/client:                 [36m<dd[39m
2021-04-04T05:01:47.6799439Z @villekulla-reservations/client:                   [33mclass[39m=[32m"css-97"[39m
2021-04-04T05:01:47.6800601Z @villekulla-reservations/client:                 [36m>[39m
2021-04-04T05:01:47.6801817Z @villekulla-reservations/client:                   [0m9:00, 5. April 2021[0m
2021-04-04T05:01:47.6802972Z @villekulla-reservations/client:                 [36m</dd>[39m
2021-04-04T05:01:47.6804101Z @villekulla-reservations/client:               [36m</div>[39m
2021-04-04T05:01:47.6805212Z @villekulla-reservations/client:               [36m<div[39m
2021-04-04T05:01:47.6806506Z @villekulla-reservations/client:                 [33mclass[39m=[32m"ms-Stack css-95"[39m
2021-04-04T05:01:47.6807953Z @villekulla-reservations/client:               [36m>[39m
2021-04-04T05:01:47.6809055Z @villekulla-reservations/client:                 [36m<dt[39m
2021-04-04T05:01:47.6810295Z @villekulla-reservations/client:                   [33mclass[39m=[32m"css-98"[39m
2021-04-04T05:01:47.6811439Z @villekulla-reservations/client:                 [36m>[39m
2021-04-04T05:01:47.6812567Z @villekulla-reservations/client:                   [0mEnde[0m
2021-04-04T05:01:47.6813711Z @villekulla-reservations/client:                 [36m</dt>[39m
2021-04-04T05:01:47.6814927Z @villekulla-reservations/client:                 [36m<dd[39m
2021-04-04T05:01:47.6816226Z @villekulla-reservations/client:                   [33mclass[39m=[32m"css-97"[39m
2021-04-04T05:01:47.6817527Z @villekulla-reservations/client:                 [36m>[39m
2021-04-04T05:01:47.6818886Z @villekulla-reservations/client:                   [0m13:30, 5. April 2021[0m
2021-04-04T05:01:47.6900612Z @villekulla-reservations/client:                 [36m</dd>[39m
2021-04-04T05:01:47.6902388Z @villekulla-reservations/client:               [36m</div>[39m
2021-04-04T05:01:47.6903649Z @villekulla-reservations/client:             [36m</dl>[39m
2021-04-04T05:01:47.6904862Z @villekulla-reservations/client:             [36m<div[39m
2021-04-04T05:01:47.6906695Z @villekulla-reservations/client:               [33mclass[39m=[32m"ms-TextField is-active ms-TextField--multiline root-100"[39m
2021-04-04T05:01:47.6908265Z @villekulla-reservations/client:             [36m>[39m
2021-04-04T05:01:47.6909576Z @villekulla-reservations/client:               [36m<div[39m
2021-04-04T05:01:47.6911449Z @villekulla-reservations/client:                 [33mclass[39m=[32m"ms-TextField-wrapper"[39m
2021-04-04T05:01:47.6912728Z @villekulla-reservations/client:               [36m>[39m
2021-04-04T05:01:47.6913875Z @villekulla-reservations/client:                 [36m<label[39m
2021-04-04T05:01:47.6915230Z @villekulla-reservations/client:                   [33mclass[39m=[32m"ms-Label root-111"[39m
2021-04-04T05:01:47.6917017Z @villekulla-reservations/client:                   [33mfor[39m=[32m"description"[39m
2021-04-04T05:01:47.6918572Z @villekulla-reservations/client:                   [33mid[39m=[32m"TextFieldLabel11"[39m
2021-04-04T05:01:47.6919752Z @villekulla-reservations/client:                 [36m>[39m
2021-04-04T05:01:47.6921237Z @villekulla-reservations/client:                   [0mBeschreibung[0m
2021-04-04T05:01:47.6922463Z @villekulla-reservations/client:                 [36m</label>[39m
2021-04-04T05:01:47.6923603Z @villekulla-reservations/client:                 [36m<div[39m
2021-04-04T05:01:47.6925198Z @villekulla-reservations/client:                   [33mclass[39m=[32m"ms-TextField-fieldGroup fieldGroup-122"[39m
2021-04-04T05:01:47.6926605Z @villekulla-reservations/client:                 [36m>[39m
2021-04-04T05:01:47.6927769Z @villekulla-reservations/client:                   [36m<textarea[39m
2021-04-04T05:01:47.6929589Z @villekulla-reservations/client:                     [33maria-invalid[39m=[32m"false"[39m
2021-04-04T05:01:47.6931732Z @villekulla-reservations/client:                     [33maria-labelledby[39m=[32m"TextFieldLabel11"[39m
2021-04-04T05:01:47.6933427Z @villekulla-reservations/client:                     [33mclass[39m=[32m"ms-TextField-field field-123"[39m
2021-04-04T05:01:47.6934896Z @villekulla-reservations/client:                     [33mid[39m=[32m"description"[39m
2021-04-04T05:01:47.6936409Z @villekulla-reservations/client:                     [33mname[39m=[32m"description"[39m
2021-04-04T05:01:47.6938095Z @villekulla-reservations/client:                     [33mstyle[39m=[32m"height: 0px;"[39m
2021-04-04T05:01:47.6939415Z @villekulla-reservations/client:                   [36m/>[39m
2021-04-04T05:01:47.7026631Z @villekulla-reservations/client:                 [36m</div>[39m
2021-04-04T05:01:47.7029535Z @villekulla-reservations/client:               [36m</div>[39m
2021-04-04T05:01:47.7030687Z @villekulla-reservations/client:             [36m</div>[39m
2021-04-04T05:01:47.7031861Z @villekulla-reservations/client:           [36m</fieldset>[39m
2021-04-04T05:01:47.7032997Z @villekulla-reservations/client:           [36m<div[39m
2021-04-04T05:01:47.7034309Z @villekulla-reservations/client:             [33mclass[39m=[32m"ms-Stack css-112"[39m
2021-04-04T05:01:47.7035983Z @villekulla-reservations/client:           [36m>[39m
2021-04-04T05:01:47.7037120Z @villekulla-reservations/client:             [36m<button[39m
2021-04-04T05:01:47.7038831Z @villekulla-reservations/client:               [33mclass[39m=[32m"ms-Button ms-Button--default root-113"[39m
2021-04-04T05:01:47.7040455Z @villekulla-reservations/client:               [33mdata-is-focusable[39m=[32m"true"[39m
2021-04-04T05:01:47.7041832Z @villekulla-reservations/client:               [33mtype[39m=[32m"reset"[39m
2021-04-04T05:01:47.7042994Z @villekulla-reservations/client:             [36m>[39m
2021-04-04T05:01:47.7044110Z @villekulla-reservations/client:               [36m<span[39m
2021-04-04T05:01:47.7045730Z @villekulla-reservations/client:                 [33mclass[39m=[32m"ms-Button-flexContainer flexContainer-114"[39m
2021-04-04T05:01:47.7047546Z @villekulla-reservations/client:                 [33mdata-automationid[39m=[32m"splitbuttonprimary"[39m
2021-04-04T05:01:47.7051423Z @villekulla-reservations/client:               [36m>[39m
2021-04-04T05:01:47.7053061Z @villekulla-reservations/client:                 [36m<span[39m
2021-04-04T05:01:47.7056145Z @villekulla-reservations/client:                   [33mclass[39m=[32m"ms-Button-textContainer textContainer-115"[39m
2021-04-04T05:01:47.7057656Z @villekulla-reservations/client:                 [36m>[39m
2021-04-04T05:01:47.7058799Z @villekulla-reservations/client:                   [36m<span[39m
2021-04-04T05:01:47.7060395Z @villekulla-reservations/client:                     [33mclass[39m=[32m"ms-Button-label label-117"[39m
2021-04-04T05:01:47.7061835Z @villekulla-reservations/client:                     [33mid[39m=[32m"id__12"[39m
2021-04-04T05:01:47.7063014Z @villekulla-reservations/client:                   [36m>[39m
2021-04-04T05:01:47.7064204Z @villekulla-reservations/client:                     [0mAbbrechen[0m
2021-04-04T05:01:47.7066652Z @villekulla-reservations/client:                   [36m</span>[39m
2021-04-04T05:01:47.7067827Z @villekulla-reservations/client:                 [36m</span>[39m
2021-04-04T05:01:47.7068992Z @villekulla-reservations/client:               [36m</span>[39m
2021-04-04T05:01:47.7070139Z @villekulla-reservations/client:             [36m</button>[39m
2021-04-04T05:01:47.7071292Z @villekulla-reservations/client:             [36m<button[39m
2021-04-04T05:01:47.7072797Z @villekulla-reservations/client:               [33mclass[39m=[32m"ms-Button ms-Button--primary root-121"[39m
2021-04-04T05:01:47.7074355Z @villekulla-reservations/client:               [33mdata-is-focusable[39m=[32m"true"[39m
2021-04-04T05:01:47.7075802Z @villekulla-reservations/client:               [33mtype[39m=[32m"submit"[39m
2021-04-04T05:01:47.7076934Z @villekulla-reservations/client:             [36m>[39m
2021-04-04T05:01:47.7078062Z @villekulla-reservations/client:               [36m<span[39m
2021-04-04T05:01:47.7079720Z @villekulla-reservations/client:                 [33mclass[39m=[32m"ms-Button-flexContainer flexContainer-114"[39m
2021-04-04T05:01:47.7081556Z @villekulla-reservations/client:                 [33mdata-automationid[39m=[32m"splitbuttonprimary"[39m
2021-04-04T05:01:47.7082922Z @villekulla-reservations/client:               [36m>[39m
2021-04-04T05:01:47.7084039Z @villekulla-reservations/client:                 [36m<span[39m
2021-04-04T05:01:47.7085663Z @villekulla-reservations/client:                   [33mclass[39m=[32m"ms-Button-textContainer textContainer-115"[39m
2021-04-04T05:01:47.7087367Z @villekulla-reservations/client:                 [36m>[39m
2021-04-04T05:01:47.7088498Z @villekulla-reservations/client:                   [36m<span[39m
2021-04-04T05:01:47.7089916Z @villekulla-reservations/client:                     [33mclass[39m=[32m"ms-Button-label label-117"[39m
2021-04-04T05:01:47.7091289Z @villekulla-reservations/client:                     [33mid[39m=[32m"id__15"[39m
2021-04-04T05:01:47.7092421Z @villekulla-reservations/client:                   [36m>[39m
2021-04-04T05:01:47.7093624Z @villekulla-reservations/client:                     [0mSpeichern[0m
2021-04-04T05:01:47.7094929Z @villekulla-reservations/client:                   [36m</span>[39m
2021-04-04T05:01:47.7096157Z @villekulla-reservations/client:                 [36m</span>[39m
2021-04-04T05:01:47.7097317Z @villekulla-reservations/client:               [36m</span>[39m
2021-04-04T05:01:47.7098451Z @villekulla-reservations/client:             [36m</button>[39m
2021-04-04T05:01:47.7099598Z @villekulla-reservations/client:           [36m</div>[39m
2021-04-04T05:01:47.7182106Z @villekulla-reservations/client:         [36m</form>[39m
2021-04-04T05:01:47.7183307Z @villekulla-reservations/client:       [36m</div>[39m
2021-04-04T05:01:47.7184426Z @villekulla-reservations/client:     [36m</body>[39m
2021-04-04T05:01:47.7185503Z @villekulla-reservations/client:       111 |     });
2021-04-04T05:01:47.7186543Z @villekulla-reservations/client:       112 |
2021-04-04T05:01:47.7187746Z @villekulla-reservations/client:     > 113 |     screen.getByText(
2021-04-04T05:01:47.7188937Z @villekulla-reservations/client:           |            ^
2021-04-04T05:01:47.7190530Z @villekulla-reservations/client:       114 |       'Die Buchung überschneidet sich mit einer existierenden Buchung.'
2021-04-04T05:01:47.7191893Z @villekulla-reservations/client:       115 |     );
2021-04-04T05:01:47.7192951Z @villekulla-reservations/client:       116 |   });
2021-04-04T05:01:47.7194623Z @villekulla-reservations/client:       at Object.getElementError (../node_modules/@testing-library/dom/dist/config.js:37:19)
2021-04-04T05:01:47.7196563Z @villekulla-reservations/client:       at ../node_modules/@testing-library/dom/dist/query-helpers.js:90:38
2021-04-04T05:01:47.7199131Z @villekulla-reservations/client:       at ../node_modules/@testing-library/dom/dist/query-helpers.js:62:17
2021-04-04T05:01:47.7202843Z @villekulla-reservations/client:       at getByText (../node_modules/@testing-library/dom/dist/query-helpers.js:111:19)
2021-04-04T05:01:47.7206181Z @villekulla-reservations/client:       at Object.<anonymous> (src/pages/__tests__/reservation-page.test.tsx:113:12)
</code></pre>
</details>

<details>
<summary>log II</summary>
<pre><code>
FAIL src/pages/__tests__/login-page.test.tsx
@villekulla-reservations/client:   ● Resource Page › should successfully log in the user
@villekulla-reservations/client:     expect(jest.fn()).toHaveBeenCalledWith(...expected)
@villekulla-reservations/client:     Expected: "/events/4zrtsev65z"
@villekulla-reservations/client:     Number of calls: 0
@villekulla-reservations/client:       57 |
@villekulla-reservations/client:       58 |     await expect(scopeIsDone(scope)).resolves.toBe(true);
@villekulla-reservations/client:     > 59 |     expect(redirect).toHaveBeenCalledWith(from);
@villekulla-reservations/client:          |                      ^
@villekulla-reservations/client:       60 |   });
@villekulla-reservations/client:       61 |
@villekulla-reservations/client:       62 |   it('should warn if the user is not verified', async () => {
@villekulla-reservations/client:       at Object.<anonymous> (src/pages/__tests__/login-page.test.tsx:59:22)
</code></pre>
</details>

**Comment by herschel666** [comment]
seems fixed 😎
